Set Socket priority using SO_PRIORITY
wires-se/p-net pull request #10
Opened 2024-06-12 07:23 UTC by ahmkar94

Set socket priority using SO_PRIORITY:
- Added setsockopt call to set SO_PRIORITY to 6 for the socket in pnal_eth_init function.
- The socket priority is set immediately after socket creation and before other configurations.

2024-06-12 07:50 UTC, troglobit requested changes
This change looks good, but you need to describe *why* the change is made.  The summary line is OK, but there's no need to repeat what we can see in the code diff.  

Something along the lines of: "Ensure all DCP frames generated by the P-Net stack have elevated priority compared to normal traffic.  Not higher than 6, to not cause interruptions on level 7, where MRP and other network control protocols reside."

Maybe also quote the PROFINET standard, citing the QoS requirements for conformance.  But that should possibly go in the code itself as a comment.

2024-06-18 09:37 UTC, troglobit requested changes
Looks much better, a good comment in the code clearly describing the why this the sockopt is needed, followed by a well written commit message.  Well done!

Only one thing left: formatting!  Please consider the following seven golden rules https://cbea.ms/git-commit/#seven-rules, in particular line lengths.

2024-06-18 12:55 UTC, ahmkar94 commented
Hope it looks better now :)

2024-06-18 13:29 UTC, troglobit approved these changes
Perfect! :1st_place_medal:

2024-06-18 13:29 UTC, merged